logLevel: info

api: yes
apiAddress: :9997

rtmp: yes
rtmpAddress: :1935

hls: yes
hlsAddress: :8888

webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: :8189

rtsp: no

paths:
  all:
    source: publisher
    record: no
